#!/usr/bin/env bash
# argus — fetch runtime secrets from Azure Key Vault via the VM Managed Identity → credential FILES.
#
# Runs as a boot-time systemd oneshot (argus-secrets.service), BEFORE the Compose stack + the backup/cleanup
# units. It is the "separate fetch step" the backup/cleanup units already reference: it materialises
# /run/argus/secrets/* from Key Vault. The stack + workers then read those files (compose Docker secrets /
# *_FILE env / systemd LoadCredential). See infra/vm/secrets/README.md + docs/threat-models/vm-secrets.md.
#
# Security model:
#   - NO static credentials. The access token is minted by the VM's Managed Identity via IMDS
#     (169.254.169.254) — link-local, on-box only — and is scoped to vault.azure.net (read).
#   - Secret VALUES are written to tmpfs (/run, never disk-backed) at mode 0444 owned by root. The files MUST
#     be mode 0444, not 0400: file-based Compose secrets are bind-mounted into the container with the host
#     owner/mode UNCHANGED on Linux (no uid/gid remapping — that only happens on macOS Docker Desktop's
#     file-sharing layer), and the consuming services run as NON-root (api/node uid 1000, postgres uid 999,
#     grafana uid 472, redis uid 999), so a root-owned 0400 file would be unreadable and the stack would fail
#     to start. Confinement is the 0700 root tmpfs SECRETS_DIR (host non-root users can't traverse it; the
#     Docker daemon mounts as root), NOT the file mode. Values are written ATOMICALLY (temp + mv) and
#     are NEVER exported to the environment (so not in /proc/<pid>/environ, not inherited by children) nor
#     placed in argv. Logs carry secret NAMES + HTTP status ONLY — never a value (invariant #2/#5).
#   - FAIL CLOSED: any failed fetch or empty value exits non-zero. The stack/backup units declare
#     Requires=argus-secrets.service, so they never start on a stale/missing secret.
#
# Requires: curl + jq (installed by cloud-init). Config via the systemd unit's Environment=:
#   ARGUS_KEY_VAULT   the Key Vault NAME (non-secret), e.g. argus-kv-ab12cd  [required]
#   ARGUS_SECRETS_DIR target dir (default /run/argus/secrets)
set -euo pipefail

SECRETS_DIR="${ARGUS_SECRETS_DIR:-/run/argus/secrets}"
: "${ARGUS_KEY_VAULT:?ARGUS_KEY_VAULT required (the Key Vault name)}"
KV_API_VERSION="${KV_API_VERSION:-7.4}"
IMDS_URL="http://169.254.169.254/metadata/identity/oauth2/token"
VAULT_URL="https://${ARGUS_KEY_VAULT}.vault.azure.net"

# Key Vault secret name -> local credential filename (in $SECRETS_DIR). KV names are kebab-case (Key Vault
# disallows underscores); local filenames match what each consumer expects:
#   compose Docker secrets: postgres_password, database_url, s3_secret_access_key, zitadel_masterkey,
#                           zitadel_db_password
#   cloudflared + zitadel runtime values (stack launcher reads them): tunnel_token, zitadel_db_password (also
#                           a compose secret — postgres reads the file, Zitadel reads the value as env),
#                           zitadel_admin_password (first-init bootstrap only)
#   backup/cleanup LoadCredential sources: backup-db-password, cleanup-db-password, b2-app-key
SECRETS=(
  "argus-postgres-owner-password=postgres_password"
  "argus-database-url=database_url"
  "argus-s3-secret-access-key=s3_secret_access_key"
  "argus-redis-password=redis_password"
  "argus-tunnel-token=tunnel_token"
  "argus-zitadel-masterkey=zitadel_masterkey"
  "argus-zitadel-db-password=zitadel_db_password"
  "argus-zitadel-admin-password=zitadel_admin_password"
  "argus-grafana-admin-password=grafana_admin_password"
  "argus-backup-db-password=backup-db-password"
  "argus-cleanup-db-password=cleanup-db-password"
  "argus-b2-app-key=b2-app-key"
  # GlitchTip (roadmap #48 Slice B) — dedicated Postgres password + Django SECRET_KEY.
  # The DATABASE_URL is GENERATED by deploy.sh from glitchtip_db_password (same pattern as redis_url).
  "argus-glitchtip-db-password=glitchtip_db_password"
  "argus-glitchtip-secret-key=glitchtip_secret_key"
)

# OPTIONAL secrets — may be ABSENT on a first boot (provisioned later). Unlike the mandatory set, an absent
# value is NOT fatal: we seed an EMPTY 0444 file so the compose secret mount still resolves, and the consumer
# runs degraded until the value is provisioned. Used for the Zitadel Login V2 service-user PAT, which Zitadel
# only mints AFTER first init — the operator stores it in Key Vault during arming (see vm-zitadel.md).
OPTIONAL_SECRETS=(
  "argus-zitadel-login-pat=zitadel_login_pat"
  # GlitchTip project DSN — a write-only ingest key the operator creates in the GlitchTip UI after
  # the first deploy (arming). Seeded EMPTY until provisioned; the api is a complete no-op without it.
  "argus-sentry-dsn=sentry_dsn"
  # G2 SSO: Zitadel Management API PAT for org+IdP provisioning. Seeded EMPTY until the operator runs
  # provision.sh and stores the admin PAT in Key Vault. SSO endpoints return 503 when empty.
  "argus-zitadel-management-pat=zitadel_management_pat"
)

log() { printf 'argus-secrets: %s\n' "$*" >&2; } # names/status only — NEVER a secret value

cleanup() { rm -f "${SECRETS_DIR}"/.tmp.* 2>/dev/null || true; }
trap cleanup EXIT

# Under the systemd unit, `RuntimeDirectory=argus/secrets` already created this dir (root:root 0700) before
# ExecStart — surviving a reboot that wipes /run. This install -d is just a fallback for a MANUAL run outside
# systemd; root:root 0700 with NO chgrp (the unit's empty CapabilityBoundingSet drops CAP_CHOWN). The 0700
# dir is the real confinement boundary — host non-root users can't traverse it; the root Docker daemon can,
# so it bind-mounts the 0444 secret files into containers where the non-root service users read them.
install -d -m 0700 "$SECRETS_DIR"
umask 0077

# --- 1. Managed-Identity access token for Key Vault (no static creds). ---
token_json="$(curl -fsS --max-time 15 --retry 3 --retry-connrefused --retry-delay 2 -H 'Metadata: true' \
  "${IMDS_URL}?api-version=2018-02-01&resource=https%3A%2F%2Fvault.azure.net")" || {
  log "FATAL: could not obtain a Managed Identity token from IMDS"
  exit 1
}
access_token="$(printf '%s' "$token_json" | jq -r '.access_token // empty')"
token_json=""
[ -n "$access_token" ] || {
  log "FATAL: IMDS returned no access_token"
  exit 1
}

# --- 2. Fetch each secret → atomic 0444 root file (see header: non-root containers must read it via bind
#        mount). Fail closed on the first error. ---
for entry in "${SECRETS[@]}"; do
  kv_name="${entry%%=*}"
  file="${entry##*=}"
  dest="${SECRETS_DIR}/${file}"
  tmp="${SECRETS_DIR}/.tmp.${file}.$$"

  # Pass the Bearer token via curl --config on STDIN (a heredoc), never -H on argv — so the Managed-Identity
  # token can't be read from /proc/<pid>/cmdline by another process during the call.
  resp="$(curl -fsS --max-time 15 --retry 3 --retry-connrefused --retry-delay 2 --config - \
    "${VAULT_URL}/secrets/${kv_name}?api-version=${KV_API_VERSION}" <<EOF
header = "Authorization: Bearer ${access_token}"
EOF
  )" || {
    log "FATAL: fetch failed for '${kv_name}'"
    exit 1
  }
  # $(...) strips the trailing newline jq -r emits, so no spurious newline lands in the file (Postgres reads
  # POSTGRES_PASSWORD_FILE verbatim — a trailing newline would corrupt the password).
  value="$(printf '%s' "$resp" | jq -r '.value // empty')"
  resp=""
  [ -n "$value" ] || {
    log "FATAL: '${kv_name}' is missing or empty in Key Vault"
    exit 1
  }

  printf '%s' "$value" >"$tmp"
  value=""
  chmod 0444 "$tmp"
  mv -f "$tmp" "$dest" # atomic replace (rotation-safe)
  log "delivered ${kv_name} -> ${file}"
done

# --- 3. Optional secrets: a value that hasn't been provisioned YET (HTTP 404) is OK on a first boot — seed an
#        empty 0444 file so the compose mount resolves (the consumer runs degraded until provisioned). But
#        distinguish that from a transient/permission error: branch on the HTTP status (no `-f`, capture
#        `%{http_code}`) so a 5xx/403/connection failure FAILS CLOSED rather than silently overwriting an
#        already-provisioned secret with an empty file (which would degrade the consumer while reporting OK). ---
for entry in "${OPTIONAL_SECRETS[@]}"; do
  kv_name="${entry%%=*}"
  file="${entry##*=}"
  dest="${SECRETS_DIR}/${file}"
  tmp="${SECRETS_DIR}/.tmp.${file}.$$"
  body="${SECRETS_DIR}/.tmp.${file}.$$.body"
  # Token via --config stdin (never argv). `|| true`: on a connection failure curl exits non-zero and writes
  # "000" to the captured status — handled as a hard error below, not a silent empty.
  http_code="$(curl -sS --max-time 15 --retry 3 --retry-connrefused --retry-delay 2 \
    -o "$body" -w '%{http_code}' --config - \
    "${VAULT_URL}/secrets/${kv_name}?api-version=${KV_API_VERSION}" <<EOF || true
header = "Authorization: Bearer ${access_token}"
EOF
  )"
  case "$http_code" in
  200)
    value="$(jq -r '.value // empty' <"$body")"
    [ -n "$value" ] || {
      log "FATAL: '${kv_name}' returned 200 but an empty value"
      rm -f "$body"
      exit 1
    }
    printf '%s' "$value" >"$tmp"
    value=""
    chmod 0444 "$tmp"
    mv -f "$tmp" "$dest"
    log "delivered ${kv_name} -> ${file}"
    ;;
  404)
    if [ -s "$dest" ]; then
      # Already provisioned, but KV now 404s (accidental secret deletion / name mismatch during a restore).
      # KEEP the existing valid token rather than silently degrading login; surface it loudly so the operator
      # restores the Key Vault secret. (Deleting the KV copy doesn't invalidate the token — it lives in
      # Zitadel's DB — so the on-box file is still usable.)
      log "WARN ${kv_name} now 404s but ${file} is already populated — KEEPING the existing value; restore the Key Vault secret"
    else
      : >"$tmp" # genuinely not provisioned yet → seed EMPTY so the mount resolves (consumer degraded)
      chmod 0444 "$tmp"
      mv -f "$tmp" "$dest"
      log "optional ${kv_name} not provisioned (404) — seeded EMPTY ${file} (consumer degraded until set)"
    fi
    ;;
  *)
    # Transient/permission/connection error — do NOT clobber a possibly-provisioned secret with empty.
    log "FATAL: optional fetch for '${kv_name}' failed (HTTP ${http_code:-none}); refusing to overwrite ${file}"
    rm -f "$body" "$tmp"
    exit 1
    ;;
  esac
  rm -f "$body"
done

access_token=""
log "all secrets delivered to ${SECRETS_DIR}"
