import { randomInt } from 'node:crypto';

// Pseudonymous handle word lists (roadmap #44b). 200 adjectives × 200 animals = 40,000 unique handles per
// tenant. Family-friendly + positive. These set the POOL size only — uniqueness is GUARANTEED at the DB
// (unique (tenant_id, display_name)) + regenerate-on-conflict in UserService, not by these lists.
// TODO(scale): if a tenant approaches the 40k ceiling, add a numeric suffix or extend the lists (see
// docs/threat-models/pseudonymous-identity.md §6). Both lists are asserted unique + length-200 in the spec.

export const HANDLE_ADJECTIVES = [
  'Able',
  'Adept',
  'Agile',
  'Alert',
  'Amber',
  'Ample',
  'Amused',
  'Ardent',
  'Artful',
  'Balmy',
  'Blissful',
  'Bold',
  'Bouncy',
  'Brave',
  'Breezy',
  'Bright',
  'Brisk',
  'Bubbly',
  'Buoyant',
  'Calm',
  'Candid',
  'Canny',
  'Caring',
  'Charming',
  'Cheerful',
  'Cheery',
  'Chipper',
  'Chirpy',
  'Classic',
  'Clever',
  'Comfy',
  'Cosmic',
  'Cozy',
  'Crafty',
  'Crimson',
  'Crisp',
  'Curious',
  'Cuddly',
  'Dainty',
  'Dapper',
  'Daring',
  'Dashing',
  'Dauntless',
  'Dazzling',
  'Deft',
  'Devoted',
  'Diligent',
  'Dreamy',
  'Dulcet',
  'Dynamic',
  'Eager',
  'Earnest',
  'Easygoing',
  'Elated',
  'Electric',
  'Elegant',
  'Epic',
  'Equable',
  'Ethereal',
  'Exuberant',
  'Fabled',
  'Fair',
  'Faithful',
  'Fancy',
  'Fearless',
  'Feisty',
  'Festive',
  'Fiery',
  'Fleet',
  'Fluffy',
  'Fond',
  'Frank',
  'Free',
  'Fresh',
  'Friendly',
  'Frisky',
  'Frosty',
  'Funky',
  'Fuzzy',
  'Gallant',
  'Gentle',
  'Genuine',
  'Giddy',
  'Gleeful',
  'Glowing',
  'Golden',
  'Graceful',
  'Grand',
  'Grateful',
  'Groovy',
  'Happy',
  'Hardy',
  'Harmonic',
  'Hearty',
  'Helpful',
  'Honest',
  'Hopeful',
  'Humble',
  'Ideal',
  'Immense',
  'Intrepid',
  'Ivory',
  'Jaunty',
  'Jazzy',
  'Jolly',
  'Jovial',
  'Joyful',
  'Jubilant',
  'Keen',
  'Kind',
  'Kindly',
  'Lambent',
  'Lavish',
  'Limber',
  'Lithe',
  'Lively',
  'Lofty',
  'Loyal',
  'Lucky',
  'Lush',
  'Lustrous',
  'Magic',
  'Mellow',
  'Merry',
  'Mighty',
  'Mindful',
  'Mirthful',
  'Misty',
  'Modest',
  'Mystic',
  'Neat',
  'Nifty',
  'Nimble',
  'Noble',
  'Opal',
  'Optimal',
  'Peaceful',
  'Peppy',
  'Perky',
  'Placid',
  'Playful',
  'Plucky',
  'Plush',
  'Polished',
  'Posh',
  'Precise',
  'Proud',
  'Pure',
  'Quaint',
  'Quick',
  'Quiet',
  'Quirky',
  'Radiant',
  'Rapid',
  'Ready',
  'Regal',
  'Robust',
  'Rosy',
  'Royal',
  'Ruddy',
  'Rugged',
  'Rustic',
  'Sage',
  'Sassy',
  'Savvy',
  'Scenic',
  'Serene',
  'Sharp',
  'Shiny',
  'Silky',
  'Silver',
  'Sincere',
  'Sleek',
  'Smart',
  'Smooth',
  'Snappy',
  'Snazzy',
  'Snug',
  'Soulful',
  'Sparkly',
  'Spirited',
  'Splendid',
  'Spry',
  'Stalwart',
  'Steady',
  'Stellar',
  'Sterling',
  'Stoic',
  'Stout',
  'Sturdy',
  'Suave',
  'Sunny',
  'Super',
  'Swift',
  'Tactful',
  'Tender',
  'Thriving',
  'Tidy',
  'Tireless',
  'Tranquil',
] as const;

export const HANDLE_ANIMALS = [
  'Otter',
  'Badger',
  'Fox',
  'Wolf',
  'Bear',
  'Deer',
  'Elk',
  'Moose',
  'Bison',
  'Boar',
  'Hare',
  'Rabbit',
  'Mole',
  'Hedgehog',
  'Squirrel',
  'Chipmunk',
  'Beaver',
  'Raccoon',
  'Skunk',
  'Possum',
  'Bobcat',
  'Cougar',
  'Leopard',
  'Jaguar',
  'Cheetah',
  'Lion',
  'Tiger',
  'Lynx',
  'Puma',
  'Coyote',
  'Jackal',
  'Hyena',
  'Meerkat',
  'Mongoose',
  'Lemur',
  'Gibbon',
  'Baboon',
  'Gorilla',
  'Orangutan',
  'Chimp',
  'Sloth',
  'Armadillo',
  'Anteater',
  'Aardvark',
  'Pangolin',
  'Tapir',
  'Capybara',
  'Wombat',
  'Wallaby',
  'Koala',
  'Quokka',
  'Platypus',
  'Echidna',
  'Panda',
  'Elephant',
  'Rhino',
  'Hippo',
  'Giraffe',
  'Zebra',
  'Antelope',
  'Gazelle',
  'Impala',
  'Buffalo',
  'Yak',
  'Camel',
  'Llama',
  'Alpaca',
  'Donkey',
  'Horse',
  'Pony',
  'Goat',
  'Sheep',
  'Ferret',
  'Stoat',
  'Weasel',
  'Marten',
  'Wolverine',
  'Dormouse',
  'Shrew',
  'Porcupine',
  'Bat',
  'Walrus',
  'Seal',
  'Dolphin',
  'Whale',
  'Orca',
  'Narwhal',
  'Manatee',
  'Falcon',
  'Hawk',
  'Eagle',
  'Owl',
  'Raven',
  'Robin',
  'Sparrow',
  'Finch',
  'Wren',
  'Swallow',
  'Magpie',
  'Kestrel',
  'Heron',
  'Osprey',
  'Crane',
  'Stork',
  'Swan',
  'Goose',
  'Duck',
  'Teal',
  'Mallard',
  'Puffin',
  'Penguin',
  'Pelican',
  'Flamingo',
  'Toucan',
  'Parrot',
  'Macaw',
  'Kingfisher',
  'Woodpecker',
  'Nuthatch',
  'Starling',
  'Thrush',
  'Blackbird',
  'Lark',
  'Cuckoo',
  'Dove',
  'Pigeon',
  'Quail',
  'Pheasant',
  'Peacock',
  'Turkey',
  'Ostrich',
  'Emu',
  'Cassowary',
  'Kiwi',
  'Albatross',
  'Gull',
  'Tern',
  'Cormorant',
  'Gannet',
  'Hornbill',
  'Hoopoe',
  'Oriole',
  'Warbler',
  'Wagtail',
  'Seahorse',
  'Pufferfish',
  'Clownfish',
  'Angelfish',
  'Octopus',
  'Squid',
  'Cuttlefish',
  'Jellyfish',
  'Starfish',
  'Crab',
  'Lobster',
  'Shrimp',
  'Turtle',
  'Tortoise',
  'Gecko',
  'Iguana',
  'Chameleon',
  'Salamander',
  'Newt',
  'Frog',
  'Toad',
  'Axolotl',
  'Bee',
  'Ladybug',
  'Beetle',
  'Cricket',
  'Grasshopper',
  'Mantis',
  'Dragonfly',
  'Butterfly',
  'Moth',
  'Firefly',
  'Ant',
  'Snail',
  'Marlin',
  'Tuna',
  'Salmon',
  'Trout',
  'Perch',
  'Pike',
  'Carp',
  'Bream',
  'Minnow',
  'Sardine',
  'Herring',
  'Mackerel',
  'Cod',
  'Halibut',
  'Flounder',
  'Sole',
  'Eel',
  'Grouper',
  'Snapper',
  'Wrasse',
  'Bass',
  'Sturgeon',
] as const;

// Total pool (documented for the exhaustion-residual in pseudonymous-identity.md §6).
export const HANDLE_POOL_SIZE = HANDLE_ADJECTIVES.length * HANDLE_ANIMALS.length;

/**
 * Generate a random pseudonymous handle like "Brave Otter". Uses node:crypto.randomInt (a CSPRNG) — NEVER
 * Math.random (the argus-no-insecure-random total ban). This produces a DISPLAY label only: it is not an
 * auth identity and not key material, so it lives here in apps/api, not in packages/crypto.
 */
export function generateHandle(): string {
  const adjective = HANDLE_ADJECTIVES[randomInt(HANDLE_ADJECTIVES.length)];
  const animal = HANDLE_ANIMALS[randomInt(HANDLE_ANIMALS.length)];
  return `${adjective} ${animal}`;
}

/** The unique index whose 23505 violation means a display_name collision (within a tenant). */
export const HANDLE_UNIQUE_INDEX = 'users_tenant_display_name_idx';

/** True iff err (or any error in its .cause chain) is a Postgres 23505 against the handle index. */
export function isHandleCollision(err: unknown): boolean {
  let cur: unknown = err;
  for (let depth = 0; cur != null && depth < 5; depth++) {
    if (typeof cur !== 'object') break;
    const o = cur as {
      code?: unknown;
      constraint_name?: unknown;
      constraint?: unknown;
      cause?: unknown;
    };
    if (o.code === '23505') {
      const c =
        (typeof o.constraint_name === 'string' && o.constraint_name) ||
        (typeof o.constraint === 'string' && o.constraint) ||
        '';
      if (c === HANDLE_UNIQUE_INDEX) return true;
    }
    cur = o.cause;
  }
  return false;
}
