apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secmes
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # TODO: set to your git origin after `git init` + push.
    repoURL: https://github.com/REPLACE_ME/secmes.git
    targetRevision: main
    path: charts/secmes
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: secmes
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
