#!/usr/bin/env bash
# argus — fetch runtime secrets from Azure Key Vault via the VM Managed Identity → credential FILES.
#
# Runs as a boot-time systemd oneshot (argus-secrets.service), BEFORE the Compose stack + the backup/cleanup
# units. It is the "separate fetch step" the backup/cleanup units already reference: it materialises
# /run/argus/secrets/* from Key Vault. The stack + workers then read those files (compose Docker secrets /
# *_FILE env / systemd LoadCredential). See infra/stack/secrets/README.md + docs/threat-models/vm-secrets.md.
#
# Security model:
#   - NO static credentials. The access token is minted by a platform machine identity scoped to
#     vault.azure.net (read). Two sources, selected by ARGUS_TOKEN_SOURCE (default imds):
#       imds — the Azure VM's Managed Identity via IMDS (169.254.169.254), link-local, on-box only.
#       arc  — the box is a NON-Azure host (AWS EC2) onboarded to Azure Arc; the Arc managed identity mints
#              the token via the local HIMDS endpoint (localhost:40342) using the challenge-token handshake
#              (a 401 names a root/himds-group-only .key file we read + echo back as Basic auth). Still no
#              static credential — and the challenge file gates token minting to root/himds, stricter than IMDS.
#   - Secret VALUES are written to tmpfs (/run, never disk-backed) at mode 0444 owned by root. The files MUST
#     be mode 0444, not 0400: file-based Compose secrets are bind-mounted into the container with the host
#     owner/mode UNCHANGED on Linux (no uid/gid remapping — that only happens on macOS Docker Desktop's
#     file-sharing layer), and the consuming services run as NON-root (api/node uid 1000, postgres uid 999,
#     grafana uid 472, redis uid 999), so a root-owned 0400 file would be unreadable and the stack would fail
#     to start. Confinement is the 0700 root tmpfs SECRETS_DIR (host non-root users can't traverse it; the
#     Docker daemon mounts as root), NOT the file mode. Values are written ATOMICALLY (temp + mv) and
#     are NEVER exported to the environment (so not in /proc/<pid>/environ, not inherited by children) nor
#     placed in argv. Logs carry secret NAMES + HTTP status ONLY — never a value (invariant #2/#5).
#   - FAIL CLOSED: any failed fetch or empty value exits non-zero. The stack/backup units declare
#     Requires=argus-secrets.service, so they never start on a stale/missing secret.
#
# Requires: curl + jq (installed by cloud-init). Config via the systemd unit's Environment=:
#   ARGUS_KEY_VAULT   the Key Vault NAME (non-secret), e.g. argus-kv-ab12cd  [required]
#   ARGUS_SECRETS_DIR target dir (default /run/argus/secrets)
set -euo pipefail

SECRETS_DIR="${ARGUS_SECRETS_DIR:-/run/argus/secrets}"
: "${ARGUS_KEY_VAULT:?ARGUS_KEY_VAULT required (the Key Vault name)}"
KV_API_VERSION="${KV_API_VERSION:-7.4}"
TOKEN_SOURCE="${ARGUS_TOKEN_SOURCE:-imds}" # imds (Azure VM Managed Identity) | arc (Azure Arc HIMDS on EC2)
IMDS_URL="http://169.254.169.254/metadata/identity/oauth2/token"
ARC_IMDS_URL="http://localhost:40342/metadata/identity/oauth2/token"
VAULT_URL="https://${ARGUS_KEY_VAULT}.vault.azure.net"

# Key Vault secret name -> local credential filename (in $SECRETS_DIR). KV names are kebab-case (Key Vault
# disallows underscores); local filenames match what each consumer expects:
#   compose Docker secrets: postgres_password, database_url, s3_secret_access_key, redis_password, tunnel_token
#     (cloudflared reads tunnel_token via TUNNEL_TOKEN_FILE — a file-secret mount, not an env var)
#   backup/cleanup LoadCredential source: b2-app-key
SECRETS=(
  "argus-postgres-owner-password=postgres_password"
  "argus-database-url=database_url"
  "argus-s3-secret-access-key=s3_secret_access_key"
  "argus-redis-password=redis_password"
  "argus-tunnel-token=tunnel_token"
  "argus-grafana-admin-password=grafana_admin_password"
  "argus-b2-app-key=b2-app-key"
  # GlitchTip (roadmap #48 Slice B) — dedicated Postgres password + Django SECRET_KEY.
  # The DATABASE_URL is GENERATED by deploy.sh from glitchtip_db_password (same pattern as redis_url).
  "argus-glitchtip-db-password=glitchtip_db_password"
  "argus-glitchtip-secret-key=glitchtip_secret_key"
  # Phase 1 session tokens: Ed25519 signing key (PKCS8 PEM). Operator must generate and store this in Key Vault
  # before the first production deployment — an absent or empty key makes the API unbootable.
  # See docs/threat-models/session-tokens.md §invariant-4 for key generation instructions.
  "argus-session-signing-key=session_signing_key"
  # Signed DB backups (BKP-2 follow-up): Ed25519 signing key (PKCS8 PEM), delivered to the backup worker via
  # systemd LoadCredential. MANDATORY by design: a missing signing key hard-fails boot here rather than
  # silently shipping unverifiable backups nobody notices until a restore drill. Trade-off owned: this couples
  # whole-stack boot to a backup-only secret — acceptable because populate-keyvault.sh provisions it in the
  # same pass as every other mandatory secret, so they are never independently missing. Run populate-keyvault.sh
  # BEFORE deploying this change (idempotent skip-if-exists — no --rotate needed).
  # Precedent for Ed25519-signing-outside-packages/crypto: docs/threat-models/session-tokens.md §invariant-4.
  "argus-backup-signing-key=backup-signing-key"
  # VoIP TURN relay (VoIP V1, PR 6/14 — P0-IS). All three MUST be in Key Vault before deploying this change:
  #   argus-turn-shared-secret — provisioned by populate-keyvault.sh (generated HMAC secret, 32 chars).
  #   argus-turn-tls-cert      — fullchain PEM for turn.4rgus.com; issue with infra/stack/coturn/issue-turn-cert.sh.
  #   argus-turn-tls-key       — private key PEM matching the cert above.
  # See infra/stack/coturn/README.md for the full operator sequence (issue cert → populate KV → deploy).
  "argus-turn-shared-secret=turn_shared_secret"
  "argus-turn-tls-cert=turn_tls_cert"
  "argus-turn-tls-key=turn_tls_key"
)

# OPTIONAL secrets — may be ABSENT on a first boot (provisioned later). Unlike the mandatory set, an absent
# value is NOT fatal: we seed an EMPTY 0444 file so the compose secret mount still resolves, and the consumer
# runs degraded until the value is provisioned (e.g. the GlitchTip DSN, only created after the GlitchTip UI is
# up; the breakglass admin hash, provisioned during arming).
OPTIONAL_SECRETS=(
  # Alertmanager webhook URL (Slack incoming webhook or equivalent). Seeded EMPTY until the operator
  # provisions it in Key Vault after the first deploy. Empty = alerts visible in the Alertmanager UI
  # but no external notifications. Hot-reload via: docker compose kill -s HUP alertmanager.
  "argus-alertmanager-webhook-url=alertmanager_webhook_url"
  # GlitchTip project DSN — a write-only ingest key the operator creates in the GlitchTip UI after
  # the first deploy (arming). Seeded EMPTY until provisioned; the api is a complete no-op without it.
  "argus-sentry-dsn=sentry_dsn"
  # Phase 3 Breakglass admin: Argon2id hash (JSON) for the emergency admin login. Seeded EMPTY until
  # the operator provisions it (`pnpm --filter @argus/api generate-admin-hash > /tmp/hash.json`, then
  # store the contents in Key Vault as argus-admin-bootstrap-hash). Absent = 503 on
  # /auth/breakglass/login only; the rest of the API is unaffected. See docs/threat-models/breakglass-admin.md.
  "argus-admin-bootstrap-hash=admin_bootstrap_hash"
  # VESTIGIAL (BKP-1 remediation): the backup/cleanup workers now connect to Postgres in-container over
  # local trust (docker compose exec), so these DB passwords are no longer consumed by anything. Kept here as
  # OPTIONAL (not mandatory) so an operator can safely delete them from Key Vault without bricking boot; the
  # role logins are password-less (deploy.sh 5b). Retire fully (and drop the KV secrets + populate-keyvault
  # lines) in a follow-up. See docs/threat-models/db-backup.md §7.
  "argus-backup-db-password=backup-db-password"
  "argus-cleanup-db-password=cleanup-db-password"
  # Web push: VAPID private key. OPTIONAL — seeded empty until the operator provisions it in Key Vault.
  # Empty = PushService runs degraded (push disabled) until provisioned. No boot dependency.
  "argus-vapid-private-key=vapid_private_key"
)

log() { printf 'argus-secrets: %s\n' "$*" >&2; } # names/status only — NEVER a secret value

cleanup() { rm -f "${SECRETS_DIR}"/.tmp.* 2>/dev/null || true; }
trap cleanup EXIT

# Azure Arc managed-identity token via HIMDS (localhost:40342), with the challenge-token handshake:
#   1. unauthenticated GET → 401 + `Www-Authenticate: Basic realm=<challenge-file path>`
#   2. read that file (mode 0440, himds group / root only — we run as root) → its contents are the Basic secret
#   3. retry with `Authorization: Basic <contents>` (passed via curl --config stdin, never argv) → token JSON
# Prints the access_token on stdout; logs FATAL + returns non-zero on any failure (caller fails closed).
arc_access_token() {
  local url hdrs realm secret resp
  url="${ARC_IMDS_URL}?api-version=2020-06-01&resource=https%3A%2F%2Fvault.azure.net"
  hdrs="$(curl -sS --max-time 15 --retry 3 --retry-connrefused --retry-delay 2 \
    -D - -o /dev/null -H 'Metadata: true' "$url" | tr -d '\r')" || {
    log "FATAL: Arc HIMDS unreachable at ${ARC_IMDS_URL} (is the Arc agent Connected?)"
    return 1
  }
  realm="$(printf '%s\n' "$hdrs" | grep -i '^Www-Authenticate:' | sed -n 's/.*realm=\([^ ]*\).*/\1/p')"
  [ -n "$realm" ] || {
    log "FATAL: Arc HIMDS returned no challenge realm"
    return 1
  }
  [ -r "$realm" ] || {
    log "FATAL: cannot read Arc challenge file ${realm} (need root or the himds group)"
    return 1
  }
  secret="$(cat "$realm")"
  resp="$(curl -fsS --max-time 15 --retry 3 --retry-connrefused --retry-delay 2 \
    -H 'Metadata: true' --config - "$url" <<EOF
header = "Authorization: Basic ${secret}"
EOF
  )" || {
    log "FATAL: Arc HIMDS token request failed"
    return 1
  }
  secret=""
  printf '%s' "$resp" | jq -r '.access_token // empty'
}

# Under the systemd unit, `RuntimeDirectory=argus/secrets` already created this dir (root:root 0700) before
# ExecStart — surviving a reboot that wipes /run. This install -d is just a fallback for a MANUAL run outside
# systemd; root:root 0700 with NO chgrp (the unit's empty CapabilityBoundingSet drops CAP_CHOWN). The 0700
# dir is the real confinement boundary — host non-root users can't traverse it; the root Docker daemon can,
# so it bind-mounts the 0444 secret files into containers where the non-root service users read them.
install -d -m 0700 "$SECRETS_DIR"
umask 0077

# --- 1. Machine-identity access token for Key Vault (no static creds). Source per ARGUS_TOKEN_SOURCE. ---
case "$TOKEN_SOURCE" in
imds)
  token_json="$(curl -fsS --max-time 15 --retry 3 --retry-connrefused --retry-delay 2 -H 'Metadata: true' \
    "${IMDS_URL}?api-version=2018-02-01&resource=https%3A%2F%2Fvault.azure.net")" || {
    log "FATAL: could not obtain a Managed Identity token from IMDS"
    exit 1
  }
  access_token="$(printf '%s' "$token_json" | jq -r '.access_token // empty')"
  token_json=""
  ;;
arc)
  access_token="$(arc_access_token)" || exit 1
  ;;
*)
  log "FATAL: unknown ARGUS_TOKEN_SOURCE='${TOKEN_SOURCE}' (expected imds|arc)"
  exit 1
  ;;
esac
[ -n "$access_token" ] || {
  log "FATAL: no access_token from token source '${TOKEN_SOURCE}'"
  exit 1
}

# --- 2. Fetch each secret → atomic 0444 root file (see header: non-root containers must read it via bind
#        mount). Fail closed on the first error. ---
for entry in "${SECRETS[@]}"; do
  kv_name="${entry%%=*}"
  file="${entry##*=}"
  dest="${SECRETS_DIR}/${file}"
  tmp="${SECRETS_DIR}/.tmp.${file}.$$"

  # Pass the Bearer token via curl --config on STDIN (a heredoc), never -H on argv — so the Managed-Identity
  # token can't be read from /proc/<pid>/cmdline by another process during the call.
  resp="$(curl -fsS --max-time 15 --retry 3 --retry-connrefused --retry-delay 2 --config - \
    "${VAULT_URL}/secrets/${kv_name}?api-version=${KV_API_VERSION}" <<EOF
header = "Authorization: Bearer ${access_token}"
EOF
  )" || {
    log "FATAL: fetch failed for '${kv_name}'"
    exit 1
  }
  # $(...) strips the trailing newline jq -r emits, so no spurious newline lands in the file (Postgres reads
  # POSTGRES_PASSWORD_FILE verbatim — a trailing newline would corrupt the password).
  value="$(printf '%s' "$resp" | jq -r '.value // empty')"
  resp=""
  [ -n "$value" ] || {
    log "FATAL: '${kv_name}' is missing or empty in Key Vault"
    exit 1
  }

  printf '%s' "$value" >"$tmp"
  value=""
  chmod 0444 "$tmp"
  mv -f "$tmp" "$dest" # atomic replace (rotation-safe)
  log "delivered ${kv_name} -> ${file}"
done

# --- 3. Optional secrets: a value that hasn't been provisioned YET (HTTP 404) is OK on a first boot — seed an
#        empty 0444 file so the compose mount resolves (the consumer runs degraded until provisioned). But
#        distinguish that from a transient/permission error: branch on the HTTP status (no `-f`, capture
#        `%{http_code}`) so a 5xx/403/connection failure FAILS CLOSED rather than silently overwriting an
#        already-provisioned secret with an empty file (which would degrade the consumer while reporting OK). ---
for entry in "${OPTIONAL_SECRETS[@]}"; do
  kv_name="${entry%%=*}"
  file="${entry##*=}"
  dest="${SECRETS_DIR}/${file}"
  tmp="${SECRETS_DIR}/.tmp.${file}.$$"
  body="${SECRETS_DIR}/.tmp.${file}.$$.body"
  # Token via --config stdin (never argv). `|| true`: on a connection failure curl exits non-zero and writes
  # "000" to the captured status — handled as a hard error below, not a silent empty.
  http_code="$(curl -sS --max-time 15 --retry 3 --retry-connrefused --retry-delay 2 \
    -o "$body" -w '%{http_code}' --config - \
    "${VAULT_URL}/secrets/${kv_name}?api-version=${KV_API_VERSION}" <<EOF || true
header = "Authorization: Bearer ${access_token}"
EOF
  )"
  case "$http_code" in
  200)
    value="$(jq -r '.value // empty' <"$body")"
    [ -n "$value" ] || {
      log "FATAL: '${kv_name}' returned 200 but an empty value"
      rm -f "$body"
      exit 1
    }
    printf '%s' "$value" >"$tmp"
    value=""
    chmod 0444 "$tmp"
    mv -f "$tmp" "$dest"
    log "delivered ${kv_name} -> ${file}"
    ;;
  404)
    was_populated=false
    [ -s "$dest" ] && was_populated=true

    if [ "$was_populated" = true ] && [ "$kv_name" != "argus-admin-bootstrap-hash" ]; then
      # Already provisioned, but KV now 404s (accidental secret deletion / name mismatch during a restore).
      # KEEP the existing value rather than silently degrading the consumer; surface it loudly so the operator
      # restores the Key Vault secret. (For tokens whose authority lives elsewhere, deleting the KV copy
      # doesn't invalidate the on-box file — so it's still usable.)
      # Exception: breakglass hash is always seeded empty on 404 (see below).
      log "WARN ${kv_name} now 404s but ${file} is already populated — KEEPING the existing value; restore the Key Vault secret"
    else
      # Not yet provisioned (never set), OR the breakglass hash was explicitly deleted from Key Vault.
      # For the breakglass hash, a 404 means the operator wants breakglass login disabled — we must
      # seed EMPTY even if a stale file exists, so ADMIN_BOOTSTRAP_HASH_FILE resolves to an empty
      # file and BreakglassService returns 503. Preserving the stale file would defeat that intent.
      : >"$tmp"
      chmod 0444 "$tmp"
      mv -f "$tmp" "$dest"
      if [ "$kv_name" = "argus-admin-bootstrap-hash" ] && [ "$was_populated" = true ]; then
        log "WARN ${kv_name} deleted from Key Vault — seeded EMPTY ${file} (breakglass login disabled; restore KV secret to re-enable)"
      else
        log "optional ${kv_name} not provisioned (404) — seeded EMPTY ${file} (consumer degraded until set)"
      fi
    fi
    ;;
  *)
    # Transient/permission/connection error — do NOT clobber a possibly-provisioned secret with empty.
    log "FATAL: optional fetch for '${kv_name}' failed (HTTP ${http_code:-none}); refusing to overwrite ${file}"
    rm -f "$body" "$tmp"
    exit 1
    ;;
  esac
  rm -f "$body"
done

access_token=""
log "all secrets delivered to ${SECRETS_DIR}"
